from playwright.sync_api import sync_playwright

html = """
<html>
    <body>
        <h1>Hello Cherbon Waters</h1>
        <p>This is a test PDF generated by headless Chrome.</p>
    </body>
</html>
"""

with sync_playwright() as p:
    browser = p.chromium.launch()
    page = browser.new_page()
    page.set_content(html)
    page.pdf(path="test_output.pdf", format="A4", landscape=True)
    browser.close()

print("PDF generated: test_output.pdf")
